name: CI

on: [push, pull_request]

jobs:
  continuous_integration_build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, jruby-head]
        operating-system: [windows-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: cat D:\a\jruby_test\jruby_test\vendor\bundle\jruby\2.6.0\bin\rake
        if: matrix.ruby == 'jruby-head'
      - run: ls D:\a\jruby_test\jruby_test\vendor\bundle\jruby\2.6.0\bin
        if: matrix.ruby == 'jruby-head'
      - run: cat D:/a/jruby_test/jruby_test/vendor/bundle/jruby/2.6.0/gems/rake-12.3.3/exe/rake
        if: matrix.ruby == 'jruby-head'

      - name: Run Build
        run: bundle exec rake build --trace
        shell: bash
